### PR TITLE
treat citext columns like text columns

### PR DESCRIPTION
**Pull request by jcrate**
This works for automatically searching `citext` columns as well as string and text columns.

Fixes problem listed in #676.

### CODE REVIEW

**Comment by scambra** [comment]
There are other lines which must be changed so citext columns work as text columns.

Line 341 in ActiveScaffold::DataStructures::Column, so citext columns default to :textarea form_ui as text columns.
Line 46 in SearchColumnHelpers, and line 42 in FormColumnHelpers, so citext get same html attributes as text column.

And there are some helpers defined for text columns, so an alias method should be created so citext columns use same helper.

ShowColumnHelpers, active_scaffold_show_text, create active_scaffold_show_citext alias
ListColumnHelpers, active_scaffold_column_text, create active_scaffold_column_citext alias
SearchColumnHelpers, active_scaffold_search_text, create active_scaffold_search_citext alias

**Comment by scambra** [comment]
I'm thinking `text_types.include?(column.column.type)` in SearchColumnHelpers and FormColumnHelpers could be changd to `column.text? || column.number?` or `column.text? || column.column_number?`, so no need to keep those array of column types in the helpers.

**Comment by jcrate** [comment]
I always specify full list/create/update column lists so I guess that's why I didn't run into any other problems.

Would you be opposed to handling `citext` columns as string instead of text? I believe the only real difference is using `text_field_tag` instead of `text_area_tag`.

**Comment by scambra** [comment]
That's ok, I didn't know about citext, as postgres doesn't have a case-insensitive type like varchar, which is string in rails, citext could behave by default as string, so don't default form_ui to textarea, and don't make alias in list and show column helpers.

These changes may make sense, as they apply to string and text columns:

Line 46 in SearchColumnHelpers, and line 42 in FormColumnHelpers, changing check with column.text? || column.column_number? instead of checking text_types array.

And there are some helpers defined for text columns, so an alias method should be created so citext columns use same helper.

SearchColumnHelpers, add an alias active_scaffold_search_citext to active_scaffold_search_range, so it behave as string field, similar to this line

`alias active_scaffold_search_string active_scaffold_search_range`

**Comment by jcrate** [comment]
In Postgres `citext` is case insensitive text. However, personally I generally use it for fields like names or SKUs or whatever that I don't want to always have to query with standardized case or `ILIKE`. 

Even though querying citext with LIKE or ILIKE will give the same result, I don't think we need to add any special handling. As long as it's treated like a string or text field, queries will be fine. Since I mostly use it where I'd otherwise use a Postgres string field I'd prefer not to use textarea by default but I can always go set the form_ui for them just like I've had to do for a lot of text fields.

I'll try to get the rest of those changes made this weekend and added to the pull request.

**Comment by jcrate** [comment]
Sorry I took so long to get back to this, I made the updates to the `SearchColumnHelpers` and `FormColumnHelpers` files you suggested.

**Comment by scambra** [comment]
I couldn't merge this, but I have picked the commits

**Comment by jcrate** [comment]
Thanks. Sorry it wasn't a clean PR, I think I forgot to make a new fork before I started. I'll try to remember to prep properly next time.

**Pull request closed without merging**
