### PR TITLE
Updating rubygems and bundler to the latest versions before setting up test environment

### PR DESCRIPTION
**Pull request by korobkov**

### CODE REVIEW

**Comment by scambra** [comment]
Can you explain the point in this?

**Comment by korobkov** [comment]
It's just a part of my own development/testing practice: to use latest and greatest versions of all software I use. So for me upgrading rubygems and bundler is just ordinary example of using lastest features and having fixed old bugs.
I myself prefer to rely on the same bundler/rubygems versions in testing environment that I already had tested on my own machine, rather than using very old and unknown for me version preinstalled in test woker containers.

As you may not be as happy with the latest versions of software as I am, I could also propose to stick to not necessary the latest rubygems/bundler, but to one of rather fresh ones, which you like and see to work for you, while still supporting rather fresh features.

Resume:
For me there are 2 reasons behind this:
* Using the latest and greatest rubygems/bundler
* Using not the old random preinstalled versions of them, but the ones I'm developing/tesing with on my own machine.

For you — probably, only the latest one, but who knows? :)

**Comment by korobkov** [comment]
Originally, it was not my idea: I've read about it here: https://docs.travis-ci.com/user/languages/ruby (Upgrading RubyGems)

**Comment by scambra** [comment]
travis tries to keep rubygems and bundler updated, so I don't see the point on having slower tests for this, for example, last run for master has same rubygems and bundler version are this pull request, without updating them

**Comment by korobkov** [comment]
Thank you! :)

**Comment by scambra** [comment]
@korobkov I'm trying to contact you but I can't send you an email, can you write me?

**Comment by scambra** [comment]
This change was giving troubles on some ruby versions with main Gemfile only, quite odd.
Build is https://travis-ci.org/activescaffold/active_scaffold/builds/115902981

ruby-2.3, jruby-9 and rbx-2 has bundler 1.11.2 before update gem version, and after update gem and bundler, version is 1.6.9, then fails on bundle install

Removing this change, it works for every ruby version:
https://travis-ci.org/activescaffold/active_scaffold/builds/116064344

**Comment by korobkov** [comment]
Sorry for the late answer…
I experienced the same issue with my own projects.
But even without it I have to agree with you at the point that it's not a business of an application/library to update it's build/testing environment.
I think it's testing image that shoud be updated regularly instead.
So I agree that my this proposition wasn't right and proper way to do things. :)

P.S. For my own projects I'm experimenting with custom docker images and CI builds on Gitlab.

**Comment by scambra** [comment]
Ok, I will let in this way, without updating rubygems

**Pull request merged**
