### PR TITLE
removing ActiveSupport::PerThreadRegistry

### PR DESCRIPTION
**Pull request by dgm**
Leaning on RequestStore and thread_mattr_accessor to provide thread safe access to globalish registry items.

ref: #715

### CODE REVIEW

**Comment by scambra** [comment]
I rather moving attr accessors to class methods with RequestStore too

**Comment by scambra** [comment]
I have read about thread_mattr_accessor and no need to use RequestStore, it's good like this.

**Comment by scambra** [comment]
The methods using RequestStore could probably use thread_mattr_accessor with default value, but cache method may be harder without RequestStore, so this way is good enough

**Comment by dgm** [comment]
I thought about that but one reason for RequestStore, in addition to the thread storage, is resetting the store every request...  I don't know the internals enough to know if that distinction is  important here or not.   But thanks for the merge!

**Comment by scambra** [comment]
The Registry instance was using RequestStore.store, so all data was reset on every request. Although the attr_accessors were set on every request, so resetting them may be not important for them. For example, current_ability_proc is set on every request with a prepend_before_action callback, like this one:

```ruby
        def self.included(base)
          base.prepend_before_action :assign_current_user_to_models
        end

        # We need to give the ActiveRecord classes a handle to the current user. We don't want to just pass the object,
        # because the object may change (someone may log in or out). So we give ActiveRecord a proc that ties to the
        # current_user_method on this ApplicationController.
        def assign_current_user_to_models
          ActiveScaffold::Registry.current_user_proc = proc { send(ActiveRecordPermissions.current_user_method) }
        end
```

So it may not matter to leave them for the next request, although the code using PerThreadRegistry was resetting them.

**Pull request merged**
