### PR TITLE
Enabled bundler caching to speedup builds

### PR DESCRIPTION
**Pull request by korobkov**
Up to several times faster on smaller builds. Total overall 2 times faster!!
But seems to not work on rbx-2.2 for some bundler issue (even with the latest stable bundler).
Proposed workaround is to allow failures for rbx-2.2 to speedup builds for all other build matrix cells.

What do you say? Could we allow failing on rbx-2.2? Is this version actual, as now we are sure AS works rather well on newer rubinus versions: rbx-2.4 and rbx-2.5? May be  it's somehow possible to fix this bundler issue another way?

### CODE REVIEW

**Comment by scambra** [comment]
I have no problem with failing rbx-2.2, even I would remove testing against rbx-2.2, if rbx-2.4 or 2.5 would work with rails 4.1 (default Gemfile)

**Comment by scambra** [comment]
Indeed, I was testing against rbx-2.2 because testing against rbx-2 failed on rails 4.1

**Comment by korobkov** [comment]
OK. The only problem with rails 4.1 on latest rbx is some  issue with configuration files for database.
Let me try to fix it with default config for in-memory sqlite…

**Comment by scambra** [comment]
It seems like failing to set root path correctly

**Comment by korobkov** [comment]
You are right.
I'm sorry, but as I've used only RSpec and didn't test anything with minitest, so I couldn't guess how to fix it… :(

**Pull request closed without merging**
