### PR TITLE
Checking for vulnerabilities before running test suite

### PR DESCRIPTION
**Pull request by korobkov**
Any found errors will immediately stop the build, any warnings won't

### CODE REVIEW

**Comment by scambra** [comment]
I can't accept this when I know brakeman reports some vulnerabilities

**Comment by korobkov** [comment]
Current build fails are due to some bundler-related issue, not the brakeman itself.
You can see both failed and passed jobs 50/50 in the same build (https://travis-ci.org/activescaffold/active_scaffold/builds/94942774).
Rubinius, JRuby and ruby-head are always green, other MRI - always red.
What is strange: why bundler doesn't work for MRI:
```
$ bundle exec brakeman
bundler: command not found: brakeman
Install missing gem executables with `bundle install`
```
Despite the fact brakeman is actually installed during `bundle install` step in the same job!
Well, this is something here to look at more closely. Let me debug this some more time; try the newest bundler, etc…
May be, you could also make a look at your bundler setup, probably consider using binstubs (not for the brakeman and this particulal issue, but in general, for consistency of dependencies through development/test/production stages).

Anyway, you're the maintainer, I'm a contributor: for me is to propose, for you — to decide. :)

**Comment by scambra** [comment]
Ok, if you can get it working for MRI I can accept this, I see it runs brakeman but it doesn't prevent to run tests or make them to fail.

**Comment by scambra** [comment]
About binstubs, do you mean to run bundle install --binstubs and add bin to git? or change something on travis?

**Comment by korobkov** [comment]
Yes, I meant exactly what you said:
```to run bundle install --binstubs and add bin to git```

**Comment by scambra** [comment]
I added binstubs

**Comment by korobkov** [comment]
And I've fixed it to work on all the rubies :) ;)

**Pull request merged**
