### PR TITLE
Updated CI environment to the latest Rubinius (3.26)

### PR DESCRIPTION
**Pull request by korobkov**

### CODE REVIEW

**Comment by korobkov** [comment]
Sergio, if you aren't comfortable or just don't like the idea of merging these small version bumps every time, I have an idea:
I'll still update .travis.yml (and this pull request) every new version, and you would merge it only when you want (or may be, only before releasing new version of AS).

**Comment by scambra** [comment]
I tried to contact you by email, but I couldn't. I was thinking I could give you access to repository, you are sending pull requests often, and I usually don't need to ask for changes or make changes by myself. So I can give you access if you want, so you can commit.

**Comment by korobkov** [comment]
This would be very nice! :)
I never had access to any projetcs other than my own :)
Now I have plans to submit the next serie of small code fixes (Brakeman), so I could make use of your invitation very soon ;)
But if I would be able to make commits myself directly into the tree, how could I know, which ones you would and wouldn't like?

**Comment by korobkov** [comment]
It works! Thank you, Sergio! :)

**Pull request merged**
